# Generated by Django 3.0.2 on 2020-02-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_subtest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtest',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
