# Generated by Django 3.0.2 on 2020-02-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20200214_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtest',
            name='test',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='subtest', to='lab.Test'),
        ),
    ]
